############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
pageRef = "/"
weight = 1

[[main]]
name = "Activités"
pageRef = "/activite"
weight = 2

    [[main]]
    parent = "Activités"
    name = "Hifi & Son"
    pageRef = "/activite/hifi_son"
    weight = 10

     [[main]]
    parent = "Activités"
    name = "Électroménager"
    pageRef = "/activite/electromenager"
    weight = 20

    [[main]]
    parent = "Activités"
    name = "Carte Électronique"
    pageRef = "/activite/carte_electronique"
    weight = 30

    [[main]]
    parent = "Activités"
    name = "Outillage"
    pageRef = "/activite/outillage"
    weight = 40

    [[main]]
    parent = "Activités"
    name = "Objet Divers"
    pageRef = "/activite/objet_divers"
    weight = 50

[[main]]
name = "À Propos"
pageRef = "/a_propos"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

# footer menu

[[footer]]
name = "Accueil"
pageRef = "/"
weight = 1

[[footer]]
name = "Activités"
pageRef = "/activite"
weight = 2

[[footer]]
name = "À propos"
pageRef = "/a_propos"
weight = 3

[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 4

[[footer]]
name = "Certifications"
pageRef = "/certifications"
weight = 5

[[footer]]
name = "Professionnels"
pageRef = "/professionnels"
weight = 6

[[footer]]
name = "Politique de confidentialité"
pageRef = "/politique_confidentialite"
weight = 7

[[footer]]
name = "Conditions générales de vente"
pageRef = "/cgv"
weight = 8

[[footer]]
name = "Mentions légales"
pageRef = "/mentions_legales"
weight = 9