[context.deploy-preview]
publish = "public"
command = "yarn project-setup; yarn build --baseURL=$DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.2"
GO_VERSION = "1.20.5"

[context.production]
publish = "public"
command = "yarn project-setup; yarn build --baseURL=$URL"

[context.production.environment]
HUGO_VERSION = "0.121.2"
GO_VERSION = "1.20.5"
